# Generated by Django 2.2.5 on 2020-08-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200824_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Language',
            field=models.CharField(blank=True, choices=[('kr', 'korean'), ('en', 'English')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='superhost',
            field=models.BooleanField(default=False),
        ),
    ]
