# Generated by Django 2.2.5 on 2020-08-26 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='itemAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('itemabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rooms.itemAbstract')),
            ],
            options={
                'abstract': False,
            },
            bases=('rooms.itemabstract',),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('itemabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rooms.itemAbstract')),
            ],
            options={
                'abstract': False,
            },
            bases=('rooms.itemabstract',),
        ),
        migrations.CreateModel(
            name='House_rules',
            fields=[
                ('itemabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rooms.itemAbstract')),
            ],
            options={
                'abstract': False,
            },
            bases=('rooms.itemabstract',),
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('itemabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rooms.itemAbstract')),
            ],
            options={
                'abstract': False,
            },
            bases=('rooms.itemabstract',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=140)),
                ('guestes', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('check_in', models.TimeField()),
                ('instant_book', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('amenity', models.ManyToManyField(to='rooms.Amenity')),
                ('facility', models.ManyToManyField(to='rooms.Facility')),
                ('house_rules', models.ManyToManyField(to='rooms.House_rules')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.RoomType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
